export const data = [
    {
      "VIN": "5YJYGDEE1L",
      "County": "King",
      "City": "Seattle",
      "State": "WA",
      "Postal Code": "98122",
      "Model Year": 2020,
      "Make": "TESLA",
      "Model": "MODEL Y",
      "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
      "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
      "Electric Range": 291,
      "Base MSRP": 0,
      "Legislative District": 37,
      "DOL Vehicle ID": 125701579,
      "Vehicle Location": "POINT (-122.30839 47.610365)",
      "Electric Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
      "2020 Census Tract": "53033007800"
    },
    {
      "VIN": "7SAYGDEE9P",
      "County": "Snohomish",
      "City": "Bothell",
      "State": "WA",
      "Postal Code": "98021",
      "Model Year": 2023,
      "Make": "TESLA",
      "Model": "MODEL Y",
      "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
      "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Eligibility unknown as battery range has not been researched",
      "Electric Range": 0,
      "Base MSRP": 0,
      "Legislative District": 1,
      "DOL Vehicle ID": 244285107,
      "Vehicle Location": "POINT (-122.179458 47.802589)",
      "Electric Utility": "PUGET SOUND ENERGY INC",
      "2020 Census Tract": "53061051938"
    },
    {
      "VIN": "5YJSA1E4XK",
      "County": "King",
      "City": "Seattle",
      "State": "WA",
      "Postal Code": "98109",
      "Model Year": 2019,
      "Make": "TESLA",
      "Model": "MODEL S",
      "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
      "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
      "Electric Range": 270,
      "Base MSRP": 0,
      "Legislative District": 36,
      "DOL Vehicle ID": 156773144,
      "Vehicle Location": "POINT (-122.34848 47.632405)",
      "Electric Utility": "CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)",
      "2020 Census Tract": "53033006800"
    },
    {
      "VIN": "5YJSA1E27G",
      "County": "King",
      "City": "Issaquah",
      "State": "WA",
      "Postal Code": "98027",
      "Model Year": 2016,
      "Make": "TESLA",
      "Model": "MODEL S",
      "Electric Vehicle Type": "Battery Electric Vehicle (BEV)",
      "Clean Alternative Fuel Vehicle (CAFV) Eligibility": "Clean Alternative Fuel Vehicle Eligible",
      "Electric Range": 210,
      "Base MSRP": 0,
      "Legislative District": 5,
      "DOL Vehicle ID": 165103011,
      "Vehicle Location": "POINT (-122.03646 47.534065)",
      "Electric Utility": "PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)",
      "2020 Census Tract": "53033032104"
    }
  ]
  